version: '3.4'

networks:
  backend: 

services:
  hitechdb:
    container_name: hitech-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - 8001:1433
  userwebapi:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}userwebapi
    build:
      context: .
      dockerfile: UserWebAPI/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
    environment:
      - DB_HOST=hitechdb
      - DB_NAME=user
      - DB_SA_PASSWORD=password@12345# 

  blogwebapi:
    container_name: blog-api
    image: ${DOCKER_REGISTRY-}blogwebapi
    build:
      context: .
      dockerfile: BlogWebAPI/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
    environment:
      - DB_HOST=hitechdb
      - DB_NAME=blog
      - DB_SA_PASSWORD=password@12345#

