version: '3.4'

networks:
  backend: 
  
services:
  hitechdb:
    container_name: hitech-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - 8001:1433

  api.user:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}apiuser
    build:
      context: .
      dockerfile: Microservices/API.User/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
    environment:
      - DB_HOST=hitechdb
      - DB_NAME=user
      - DB_SA_PASSWORD=password@12345# 

  api.blog:
    container_name: blog-api
    image: ${DOCKER_REGISTRY-}apiblog
    build:
      context: .
      dockerfile: Microservices/API.Blog/Dockerfile
    networks:
      - backend
    ports:
      - 8003:8080
    environment:
      - DB_HOST=hitechdb
      - DB_NAME=blog
      - DB_SA_PASSWORD=password@12345#

